name: Trigger Webhook

on:
  push:
    branches:
      - main

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to target server
        run: |
          curl -X POST https://your-server-url.com/webhook \
          -H "Content-Type: application/json" \
          -d '{
                "repository": {
                  "name": "action-repo"
                },
                "pusher": {
                  "name": "techstax-user"
                },
                "head_commit": {
                  "message": "Initial push from GitHub Actions"
                },
                "ref": "refs/heads/main",
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
              }'

